// GENERATED by tool/generate_booth_icons.py from assets/icons/booth/*.svg.
// Do not edit - change or add an SVG and rerun the script.

import 'package:flutter/widgets.dart';

/// The icons drawn on the Claude Design boards, as an icon font - so they
/// drop into `Icon`, `PTButton` and `PTIconButton` wherever a Material
/// symbol went. Stroke weight is baked in (1.75 at 24), as on the boards.
abstract final class BoothIcons {
  static const add = IconData(0xE000, fontFamily: 'BoothIcons');
  static const arrowBack = IconData(0xE001, fontFamily: 'BoothIcons');
  static const arrowForward = IconData(0xE002, fontFamily: 'BoothIcons');
  static const camera = IconData(0xE003, fontFamily: 'BoothIcons');
  static const chat = IconData(0xE004, fontFamily: 'BoothIcons');
  static const check = IconData(0xE005, fontFamily: 'BoothIcons');
  static const checkBold = IconData(0xE006, fontFamily: 'BoothIcons');
  static const chevronDown = IconData(0xE007, fontFamily: 'BoothIcons');
  static const chevronLeft = IconData(0xE008, fontFamily: 'BoothIcons');
  static const chevronRight = IconData(0xE009, fontFamily: 'BoothIcons');
  static const close = IconData(0xE00A, fontFamily: 'BoothIcons');
  static const cloudUpload = IconData(0xE00B, fontFamily: 'BoothIcons');
  static const crown = IconData(0xE00C, fontFamily: 'BoothIcons');
  static const delete = IconData(0xE00D, fontFamily: 'BoothIcons');
  static const edit = IconData(0xE00E, fontFamily: 'BoothIcons');
  static const file = IconData(0xE00F, fontFamily: 'BoothIcons');
  static const film = IconData(0xE010, fontFamily: 'BoothIcons');
  static const fire = IconData(0xE011, fontFamily: 'BoothIcons');
  static const flag = IconData(0xE012, fontFamily: 'BoothIcons');
  static const forward = IconData(0xE013, fontFamily: 'BoothIcons');
  static const fullscreen = IconData(0xE014, fontFamily: 'BoothIcons');
  static const fullscreenExit = IconData(0xE015, fontFamily: 'BoothIcons');
  static const group = IconData(0xE016, fontFamily: 'BoothIcons');
  static const guest = IconData(0xE017, fontFamily: 'BoothIcons');
  static const info = IconData(0xE018, fontFamily: 'BoothIcons');
  static const leave = IconData(0xE019, fontFamily: 'BoothIcons');
  static const link = IconData(0xE01A, fontFamily: 'BoothIcons');
  static const lock = IconData(0xE01B, fontFamily: 'BoothIcons');
  static const lockFilled = IconData(0xE01C, fontFamily: 'BoothIcons');
  static const logout = IconData(0xE01D, fontFamily: 'BoothIcons');
  static const mail = IconData(0xE01E, fontFamily: 'BoothIcons');
  static const mic = IconData(0xE01F, fontFamily: 'BoothIcons');
  static const micOff = IconData(0xE020, fontFamily: 'BoothIcons');
  static const mood = IconData(0xE021, fontFamily: 'BoothIcons');
  static const moon = IconData(0xE022, fontFamily: 'BoothIcons');
  static const moreHoriz = IconData(0xE023, fontFamily: 'BoothIcons');
  static const moreVert = IconData(0xE024, fontFamily: 'BoothIcons');
  static const openInNew = IconData(0xE025, fontFamily: 'BoothIcons');
  static const pause = IconData(0xE026, fontFamily: 'BoothIcons');
  static const person = IconData(0xE027, fontFamily: 'BoothIcons');
  static const personRemove = IconData(0xE028, fontFamily: 'BoothIcons');
  static const play = IconData(0xE029, fontFamily: 'BoothIcons');
  static const playFilled = IconData(0xE02A, fontFamily: 'BoothIcons');
  static const power = IconData(0xE02B, fontFamily: 'BoothIcons');
  static const react = IconData(0xE02C, fontFamily: 'BoothIcons');
  static const remoteLock = IconData(0xE02D, fontFamily: 'BoothIcons');
  static const replay = IconData(0xE02E, fontFamily: 'BoothIcons');
  static const restore = IconData(0xE02F, fontFamily: 'BoothIcons');
  static const schedule = IconData(0xE030, fontFamily: 'BoothIcons');
  static const send = IconData(0xE031, fontFamily: 'BoothIcons');
  static const sendOutline = IconData(0xE032, fontFamily: 'BoothIcons');
  static const share = IconData(0xE033, fontFamily: 'BoothIcons');
  static const shield = IconData(0xE034, fontFamily: 'BoothIcons');
  static const speaker = IconData(0xE035, fontFamily: 'BoothIcons');
  static const star = IconData(0xE036, fontFamily: 'BoothIcons');
  static const starOutline = IconData(0xE037, fontFamily: 'BoothIcons');
  static const subtitles = IconData(0xE038, fontFamily: 'BoothIcons');
  static const subtitlesOff = IconData(0xE039, fontFamily: 'BoothIcons');
  static const ticketDelete = IconData(0xE03A, fontFamily: 'BoothIcons');
  static const trophy = IconData(0xE03B, fontFamily: 'BoothIcons');
  static const upload = IconData(0xE03C, fontFamily: 'BoothIcons');
  static const videoStack = IconData(0xE03D, fontFamily: 'BoothIcons');
  static const videocam = IconData(0xE03E, fontFamily: 'BoothIcons');
  static const videocamOff = IconData(0xE03F, fontFamily: 'BoothIcons');
  static const visibility = IconData(0xE040, fontFamily: 'BoothIcons');
  static const visibilityOff = IconData(0xE041, fontFamily: 'BoothIcons');
  static const volume = IconData(0xE042, fontFamily: 'BoothIcons');
  static const volumeOff = IconData(0xE043, fontFamily: 'BoothIcons');
  static const youtube = IconData(0xE044, fontFamily: 'BoothIcons');
}
