#!/usr/bin/env python3
"""Compile assets/icons/booth/*.svg into the BoothIcons icon font.

The SVGs are the icons drawn on the Claude Design boards (24-unit viewBox,
1.75 stroke, round caps), copied out verbatim - they are the source of truth.
This turns each one into a filled outline (strokes expanded by picosvg, so the
glyph is exactly what the SVG would paint at any size) and writes:

  assets/fonts/BoothIcons.otf       the font (CFF outlines, one glyph per SVG)
  lib/ui/booth_icons.g.dart         `BoothIcons.<name>` IconData constants

Both are build output: edit an SVG, or add one, then rerun. Needs picosvg and
fonttools - a throwaway venv is fine:

  python3 -m venv /tmp/v && /tmp/v/bin/pip install picosvg fonttools
  /tmp/v/bin/python tool/generate_booth_icons.py

Codepoints are assigned in sorted-name order from U+E000, so adding an icon
renumbers the ones after it. That is harmless - nothing stores a codepoint,
every caller goes through the generated constants.
"""

from pathlib import Path

from fontTools.fontBuilder import FontBuilder
from fontTools.pens.t2CharStringPen import T2CharStringPen
from fontTools.pens.transformPen import TransformPen
from fontTools.svgLib.path import parse_path
from picosvg.svg import SVG

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "assets/icons/booth"
FONT = ROOT / "assets/fonts/BoothIcons.otf"
DART = ROOT / "lib/ui/booth_icons.g.dart"

UPM = 960  # 40 units per SVG unit; the em box is the 24-unit viewBox
SCALE = UPM / 24
FIRST = 0xE000


def glyph_paths(svg_file: Path) -> list[str]:
    """Every path in the SVG after strokes, shapes and transforms are flattened
    into plain filled outlines."""
    pico = SVG.parse(str(svg_file)).topicosvg()
    return [shape.d for shape in pico.shapes()]


def main() -> None:
    icons = sorted(SRC.glob("*.svg"))
    names = [".notdef"] + [p.stem for p in icons]
    cmap, charstrings, metrics = {}, {}, {".notdef": (UPM, 0)}

    empty = T2CharStringPen(UPM, None)
    charstrings[".notdef"] = empty.getCharString()

    for i, svg_file in enumerate(icons):
        name = svg_file.stem
        pen = T2CharStringPen(UPM, None)
        # SVG is y-down from the top; fonts are y-up from the baseline, and the
        # glyph sits on the baseline filling the em (ascent = UPM, descent 0).
        flipped = TransformPen(pen, (SCALE, 0, 0, -SCALE, 0, UPM))
        for d in glyph_paths(svg_file):
            parse_path(d, flipped)
        charstrings[name] = pen.getCharString()
        metrics[name] = (UPM, 0)
        cmap[FIRST + i] = name

    fb = FontBuilder(UPM, isTTF=False)
    fb.setupGlyphOrder(names)
    fb.setupCharacterMap(cmap)
    fb.setupCFF("BoothIcons-Regular", {"FullName": "BoothIcons"}, charstrings, {})
    fb.setupHorizontalMetrics(metrics)
    fb.setupHorizontalHeader(ascent=UPM, descent=0)
    fb.setupNameTable({"familyName": "BoothIcons", "styleName": "Regular"})
    fb.setupOS2(sTypoAscender=UPM, sTypoDescender=0, usWinAscent=UPM, usWinDescent=0)
    fb.setupPost()
    FONT.parent.mkdir(parents=True, exist_ok=True)
    fb.save(str(FONT))

    lines = [
        "// GENERATED by tool/generate_booth_icons.py from assets/icons/booth/*.svg.",
        "// Do not edit - change or add an SVG and rerun the script.",
        "",
        "import 'package:flutter/widgets.dart';",
        "",
        "/// The icons drawn on the Claude Design boards, as an icon font - so they",
        "/// drop into `Icon`, `PTButton` and `PTIconButton` wherever a Material",
        "/// symbol went. Stroke weight is baked in (1.75 at 24), as on the boards.",
        "abstract final class BoothIcons {",
    ]
    for code, name in sorted(cmap.items()):
        camel = name.split("_")[0] + "".join(w.title() for w in name.split("_")[1:])
        lines.append(
            f"  static const {camel} = IconData(0x{code:X}, fontFamily: 'BoothIcons');"
        )
    lines += ["}", ""]
    DART.write_text("\n".join(lines))
    print(f"{len(icons)} icons -> {FONT.relative_to(ROOT)}, {DART.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
